var AppThemes = {
	"Dreadnaught":{
		"stylesheet":"Dreadnaught.css",
		"palmtheme":'dark'
	},
	"Clean":{
		"stylesheet":"Clean.css",
		"palmtheme":'light'
	},
	"OSXX":{
		"stylesheet":"OSXX.css",
		"palmtheme":'dark'
	},
	"Koto":{
		"stylesheet":"Koto.css",
		"palmtheme":'dark'
	},
	"Preware":{
		"stylesheet":"Preware.css",
		"palmtheme":'light'
	}
};